parameters:
    validator.list.valid.class: Hermes\Bundle\HermesBundle\Validator\Constraints\ListValidValidator

services:
    hermes.validator.list.valid:
        class: %validator.list.valid.class%
        parameters:
          - @doctrine.orm.entity_manager
        tags:
            - { name: validator.constraint_validator, alias: list_valid }
